//------------------------------------------------------------------------------
// <auto-generated>
// 自动生成类（请不要随意改变生成文件的内容，会被覆盖，请使用分部类实现对类的修改）
// 创建人：Zeje
// 创建时间：2016-3-28
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Zeje.DAL;

namespace Zeje.BLL
{
    /// <summary>
	/// 组织架构
    /// </summary> 
    public partial class HrOrgBLL
    {
        private readonly HrOrgDAL dal = new HrOrgDAL();
        /// <summary>构造函数
        /// </summary>
        public HrOrgBLL()
        { }
        /// <summary>添加对象
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>       
        public int Add(Zeje.Model.HrOrg model)
        {
             return dal.Add(model);
        }

        /// <summary>更新对象
        /// </summary>
        /// <param name="model"></param>
        /// <param name="where"></param>
        /// <returns></returns>       
        public int Update(Zeje.Model.HrOrg model,string where)
        {
            return dal.Update(model,where);
        }

        /// <summary>查询（所有）
        /// </summary>
        /// <returns></returns>       
        public List<Zeje.Model.HrOrg> GetALL()
        {
            return dal.GetALL();
        }
    }
}
