//------------------------------------------------------------------------------
// <auto-generated>
// 自动生成类（请不要随意改变生成文件的内容，会被覆盖，请使用分部类实现对类的修改）
// 创建人：Zeje
// 创建时间：2016-3-28
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace Zeje.Model
{
    /// <summary>组织架构表
	/// dbo.HrOrg
    /// </summary> 
    public partial class HrOrg
    {
        /// <summary>
        /// </summary>        
        public int Id { get; set; }
        /// <summary>组织编号
        /// </summary>        
        public string orgCode { get; set; }
        /// <summary>组织名称
        /// </summary>        
        public string orgName { get; set; }
        /// <summary>
        /// </summary>        
        public string parentOrgCode { get; set; }
        /// <summary>
        /// </summary>        
        public string remark { get; set; }
        /// <summary>
        /// </summary>        
        public string addPerson { get; set; }
        /// <summary>添加人
        /// </summary>        
        public DateTime addTime { get; set; }
        /// <summary>添加时间
        /// </summary>        
        public string updatePerson { get; set; }
        /// <summary>更新人
        /// </summary>        
        public DateTime updateTime { get; set; }
        /// <summary>更新时间
        /// </summary>        
        public string deletePerson { get; set; }
        /// <summary>删除人
        /// </summary>        
        public DateTime? deleteTime { get; set; }
    }
}
