//------------------------------------------------------------------------------
// <auto-generated>
// 自动生成类（请不要随意改变生成文件的内容，会被覆盖，请使用分部类实现对类的修改）
// 创建人：Zeje
// 创建时间：2016-3-28
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace Zeje.Model
{
    /// <summary>
	/// dbo.HrPositionLevel
    /// </summary> 
    public partial class HrPositionLevel
    {
        /// <summary>
        /// </summary>        
        public int id { get; set; }
        /// <summary>
        /// </summary>        
        public string code { get; set; }
        /// <summary>
        /// </summary>        
        public string name { get; set; }
        /// <summary>
        /// </summary>        
        public int? parentId { get; set; }
        /// <summary>排序号
        /// </summary>        
        public int? sortId { get; set; }
        /// <summary>添加人
        /// </summary>        
        public string addPerson { get; set; }
        /// <summary>添加时间
        /// </summary>        
        public DateTime? addTime { get; set; }
        /// <summary>更新人
        /// </summary>        
        public string updatePerson { get; set; }
        /// <summary>更新时间
        /// </summary>        
        public DateTime? updateTime { get; set; }
        /// <summary>删除人
        /// </summary>        
        public string deletePerson { get; set; }
        /// <summary>删除时间
        /// </summary>        
        public DateTime? deleteTime { get; set; }
    }
}
