//------------------------------------------------------------------------------
// <auto-generated>
// 自动生成类（请不要随意改变生成文件的内容，会被覆盖，请使用分部类实现对类的修改）
// 创建人：Zeje
// 创建时间：2016-3-28
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Dapper;
using Zeje.DBUtility;
using Zeje.Model;

namespace Zeje.DAL
{
    /// <summary>员工表
    /// </summary>
    public partial class HrStaffDAL
    {
        /// <summary>添加对象
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>       
        public int Add(HrStaff model)
        {
            StringBuilder query = new StringBuilder();
            query.Append(@"
INSERT INTO HrStaff
(
id,
staffCode,
name,
positionLevelCode,
positionCode,
isVisual,
addPerson,
addTime,
updatePerson,
updateTime,
deletePerson,
deleteTime
)
VALUES 
(
@id,
@staffCode,
@name,
@positionLevelCode,
@positionCode,
@isVisual,
@addPerson,
@addTime,
@updatePerson,
@updateTime,
@deletePerson,
@deleteTime
)
");
            var args = new DynamicParameters();
            args.Add("@id", model.id);
            args.Add("@staffCode", model.staffCode);
            args.Add("@name", model.name);
            args.Add("@positionLevelCode", model.positionLevelCode);
            args.Add("@positionCode", model.positionCode);
            args.Add("@isVisual", model.isVisual);
            args.Add("@addPerson", model.addPerson);
            args.Add("@addTime", model.addTime);
            args.Add("@updatePerson", model.updatePerson);
            args.Add("@updateTime", model.updateTime);
            args.Add("@deletePerson", model.deletePerson);
            args.Add("@deleteTime", model.deleteTime);
            using (DbBase db = new DbBase())
            {
                return db.DbConnecttion.Execute(query.ToString(), args);
            }
        }

        /// <summary>更新对象
        /// </summary>
        /// <param name="model"></param>
        /// <param name="where"></param>
        /// <returns></returns>       
        public int Update(HrStaff model,string where)
        {
            StringBuilder query = new StringBuilder();
            query.Append(@"
UPDATE HrStaff SET 
id= @id,
staffCode= @staffCode,
name= @name,
positionLevelCode= @positionLevelCode,
positionCode= @positionCode,
isVisual= @isVisual,
addPerson= @addPerson,
addTime= @addTime,
updatePerson= @updatePerson,
updateTime= @updateTime,
deletePerson= @deletePerson,
deleteTime= @deleteTime
");
            query.Append(" where " + where );

            using (DbBase db = new DbBase())
            {
                return db.DbConnecttion.Execute(query.ToString(), model);
            }
        }

        /// <summary>删除
        /// </summary>
        /// <param name="where"></param>
        /// <param name="param"></param>
        /// <returns></returns>       
        private int Delete(string where,object param)
        {
            StringBuilder query = new StringBuilder();
            query.Append(@" delete from HrStaff ");
            query.Append(" where " + where );

            using (DbBase db = new DbBase())
            {
                return db.DbConnecttion.Execute(query.ToString(), param);
            }
        }

        /// <summary>查询(单个实体)
        /// </summary>
        /// <param name="where"></param>
        /// <param name="param"></param>
        /// <param name="orderby"></param>
        /// <returns></returns>       
        public HrStaff GetModel(string where,object param,string orderby = "")
        {
            StringBuilder query = new StringBuilder();
            query.Append(@" select * from HrStaff ");
            if(!string.IsNullOrEmpty(where))
            {
                query.Append(" where ");
                query.Append( where );
            }

            if(!string.IsNullOrEmpty(orderby))
            {
                query.Append(" order by " + orderby );
            }

            using (DbBase db = new DbBase())
            {
                return db.DbConnecttion.Query<HrStaff>(query.ToString(), param).SingleOrDefault();
            }
        }

        /// <summary>查询（多个）
        /// </summary>
        /// <param name="where"></param>
        /// <param name="param"></param>
        /// <param name="orderby"></param>
        /// <returns></returns>       
        public List<HrStaff> GetList(string where,object param,string orderby = "")
        {
            StringBuilder query = new StringBuilder();
            query.Append(@" select * from HrStaff ");
            if(!string.IsNullOrEmpty(where))
            {
                query.Append(" where ");
                query.Append( where );
            }

            if(!string.IsNullOrEmpty(orderby))
            {
                query.Append(" order by " + orderby );
            }

            using (DbBase db = new DbBase())
            {
                return db.DbConnecttion.Query<HrStaff>(query.ToString(), param).ToList();
            }
        }

        /// <summary>查询（所有）
        /// </summary>
        /// <returns></returns>       
        public List<HrStaff> GetALL()
        {
            StringBuilder query = new StringBuilder();
            query.Append(@" select * from HrStaff ");

            using (DbBase db = new DbBase())
            {
                return db.DbConnecttion.Query<HrStaff>(query.ToString()).ToList();
            }
        }
    }
}
