//------------------------------------------------------------------------------
// <auto-generated>
// 自动生成类（请不要随意改变生成文件的内容，会被覆盖，请使用分部类实现对类的修改）
// 创建人：Zeje
// 创建时间：2016-3-28
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace Zeje.Model
{
    /// <summary>
	/// dbo.sysdiagrams
    /// </summary> 
    public partial class sysdiagrams
    {
        /// <summary>
        /// </summary>        
        public string name { get; set; }
        /// <summary>
        /// </summary>        
        public int principal_id { get; set; }
        /// <summary>
        /// </summary>        
        public int diagram_id { get; set; }
        /// <summary>
        /// </summary>        
        public int? version { get; set; }
        /// <summary>
        /// </summary>        
        public byte[] definition { get; set; }
    }
}
